### ISSUE TITLE
Stdev or SE to determine number of samples?

### ISSUE THREAD

**Issue by bangwim** [SMByC/AcATaMa#1]
Hi,

Firstly I'd like to appreciate you much for your hard work to create this great plugin.

I'd like to ask you for clarification regarding the quantity you use to calculate the number of samples.  In the AcATaMa plugin at the 'sampling' tab, it shows standard error for each stratum.  Alofsson et al. (2014) used standard deviation.  In its user guide (https://smbyc.github.io/AcATaMa/), particularly on the Sampling design section at "Stratified random sampling using area-based proportion",  it was mentioned that "Standard deviation of each stratum: You define the values in the table".  Olofsson provides a way to calculate the standard deviation (by using the user's accuracy conjecture),  but I am not sure for SE.  How do you actually calculate SE and how it relates to the sample number of each stratum.

Thanks,
WN

**Comment by XavierCLL** [comment]
Hi Bangwim

Thanks for the report, I just check your question and you are right, there is a little mistake in the name of the column in Acatama it is really the _standard deviation_, not _standard error_. I´m going to fix it, thanks.

**Comment by XavierCLL** [comment]
@KaterineVergara something to add to clarify the answer?

**Comment by KaterineVergara** [comment]
Yes. The right title for the  4th column of the table to calculate the stratified random sampling by area proportion is the standard deviation of each stratum _(i)_, not the standard error. The equation to calculate the standard deviation of stratum (i) has to be done according to Cochran, 1977 in Olofsson et al 2014 (denoted by _Si_), using the conjectured values of user's accuracies (denoted _Ui_).

 You can assign the _Ui_ values according to the classes that you have to evaluate and your experience with them. Olofsson suggests that   the stable classes are more accurate that the change classes, because the errors of commission are relatively common for the change classes.

**Comment by XavierCLL** [comment]
thanks for the report it and we hope to have solved your doubts
