### ISSUE TITLE
Stratified Sampling Stuck

### ISSUE THREAD

**Issue by mirrorbbo** [SMByC/AcATaMa#19]
When I try to do fixed number of samplings using the plug in, it says "The sampling process seems stuck due to sampling conditions. Do you want to continue this sampling process and never ask this again?" But when I try to continue it, QGIS becomes stuck and become unresponsive.
![image](https://github.com/SMByC/AcATaMa/assets/147657969/138bce98-88e3-4e49-88b7-c2e7efae26be)

**Comment by XavierCLL** [comment]
Hi @mirrorbbo 

This is not directly an Acatama issue, this could be due to:

- some (hard) restrictions in the sampling conditions (such as: high minimum distance respect to the sampling vs area, hard neighbors aggregations condition, hard post-stratified condition) make it impossible to reach the total of sampling set
- the extent of the image is very big, bigger than the data (or AOI) of the image, it makes the sampling process very slow, if so, reduce/clip the extent to the area of the data

is it your case? what is the image extent and the sampling configuration in Acatama?

**Comment by XavierCLL** [comment]
This issue was fixed in the latest version [v24.7](https://github.com/SMByC/AcATaMa/releases/tag/24.7) by implementing a QgsTask process for each sampling type (see more fad9a470495d88c51cff1f8d9938a2ce88745b0e)

**Comment by XavierCLL** [comment]
Hi @mirrorbbo any test about it is welcome and grateful, thanks for your report
